src/Acme/DemoBundle/Entity/User.php
<?php

namespace Acme\DemoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Table(name="user")
 * @ORM\Entity
 *
 */
class User
{
  /**
   * @ORM\Column(type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  protected $id;

  /**
   * @ORM\Column(name="username", type="string", length=255)
   */
  protected $username;

  /**
   * @ORM\Column(type="datetime",nullable=true)
   * @Gedmo\Timestampable(on="create")
   */
  private $registration_date;


  /**
   * Constructor
   */
  public function __construct()
  {
  }

  /**
   * Get id
   *
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * Set username
   *
   * @param string $username
   * @return User
   */
  public function setUsername($username)
  {
    $this->username = $username;

    return $this;
  }

  /**
   * Get username
   *
   * @return string
   */
  public function getUsername()
  {
    return $this->username;
  }

  /**
   * Set registration_date
   *
   * @return User
   */
  public function setRegistrationDate($registration_date)
  {
    $this->registration_date = $registration_date;
    return $this; // fluent interface
  }

  /**
   * Get registration_date
   *
   * @return datetime
   */
  public function getRegistrationDate()
  {
    return $this->registration_date;
  }

}

src/Acme/DemoBundle/Form/UserType.php
<?php

namespace Acme\DemoBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('username', 'text');
    }

    public function getName()
    {
        return 'user';
    }
}

src/Acme/DemoBundle/Controller/DemoController.php
<?php

namespace Acme\DemoBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;

// these import the "@Route" and "@Template" annotations
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

use Acme\DemoBundle\Form\UserType;
use Acme\DemoBundle\Entity\User;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

/**
 * Demo controller to perform users operation like add/list/view.
 */
class DemoController extends Controller
{
    /**
     * @Route("/", name="demo_list_user")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $users = $em->getRepository('AcmeDemoBundle:User')->findAll();

        return array('users' => $users);
    }

    /**
     * viewuser to see particular user information.
     *
     * @Route("/viewuser", name="demo_view_user")
     * @Method("GET")
     *
     * @return Response $response
     */
    public function viewuserAction(Request $request)
    {
        // get user id
        $userid = $request->get('userid');

        // create entity manager object.
        $em = $this->getDoctrine()->getManager();

        // check users exist or not.
        $user = $em->getRepository('AcmeDemoBundle:User')->find($userid);
        $userArr = array();
        if (count($user) > 0) {
            $userArr = array(
                'success' => true, 'id' => $user->getId(), 'username' => $user->getUsername(), 'registrationdate' => $user->getRegistrationDate()
            );
        }

        $response = new Response();
        // create a JSON-response
        $response->headers->set('Content-Type', 'application/json');
        // set json content
        $response->setContent(json_encode($userArr));
        // return json response.
        return $response;
    }

    /**
     * @Route("/adduser", name="demo_add_user")
     * @Template()
     */
    public function adduserAction()
    {
        $form = $this->get('form.factory')->create(new UserType());

        $user  = new User();
        $form = $this->createForm(new UserType(), $user);

        $request = $this->get('request');
        if ($request->isMethod('POST')) {
            $form->bind($request);
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($user);
                $em->flush();

                // if ajax request than return json response.
                if($request->isXmlHttpRequest()) {
                     $response = new Response();
                     $output = array('success' => true, 'id' => $user->getId(), 'username' => $user->getUsername(), 'registrationdate' => $user->getRegistrationDate());
                     $response->headers->set('Content-Type', 'application/json');
                     // set json content
                     $response->setContent(json_encode($output));

                     // return json response.
                     return $response;
                }

                // if no ajax request than redirect to user listing page.
                return $this->redirect($this->generateUrl('demo_list_user'));
            }
        }

        return array('form' => $form->createView());
    }
}

src/Acme/DemoBundle/Tests/Controller/DemoControllerTest.php
<?php

namespace Acme\DemoBundle\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DemoControllerTest extends WebTestCase
{
    public function testIndex()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/demo/hello/Fabien');

        $this->assertGreaterThan(0, $crawler->filter('html:contains("Hello Fabien")')->count());
    }
}

src/Acme/DemoBundle/Resources/views/Demo/adduser.html.twig
{% extends "AcmeDemoBundle::layout.html.twig" %}

{% block title "Add user" %}

{% block content %}
    <form action="{{ path('demo_add_user') }}" method="POST" id="user_form">
        {{ form_errors(form) }}

        {{ form_row(form.username) }}

        {{ form_rest(form) }}
        <button type="submit">Create</button>
    </form>
    <ul class="record_actions">
        <li>
            <a href="{{ path('demo_list_user') }}">
                Back to the user list
            </a>
        </li>
    </ul>
    <div id="result"></div>


    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script type="text/javascript">
     $(document).ready(function() {
         $("form").submit(function(e) {
             e.preventDefault();
             var urlPath = '{{ path('demo_add_user') }}';
             var $data = $(this).serialize();
             $.ajax({
                type: "POST",
                url: urlPath,
                data: $data
             }).done(function( result ) {
                if(result.success) {
                    $('#result').html('<span style="color:red;">User saved correctly!<br/></span> The data are:<br/><table><tr><td>id: '+ result.id +'</td></tr><tr><td>username: '+ result.username +'</td></tr><tr><td>registration_date: '+ result.registrationdate.date+'</td></tr></table>');
                }
             });
         });
     });
     </script>

{% endblock %}

src/Acme/DemoBundle/Resources/views/Demo/index.html.twig
{% extends "AcmeDemoBundle::layout.html.twig" %}

{% block title "Users list" %}

{% block content_header '' %}

{% block content %}

<a href="{{ path('demo_add_user') }}" style="float: right;">Add user</a>
    {% if users|length > 0 %}
        <h1 class="title">Users list</h1>
        <table tabindex="3"  id="user_data_table">
            <thead>
              <tr>
                  <th><b>User Id</b></th>
                  <th><b>User Name</b></th>
                  <th><b>Registration date</b></th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                      <td><a href="javascript:;" onClick="return performUserView('{{ user.id }}');">{{ user.id }}</a></td>
                      <td>{{ user.username }}</td>
                      <td>{{ user.registrationDate.date }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert-message">
            Sorry, no records found!
        </div>
    {% endif %}

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script type="text/javascript">
        function performUserView(userId)
        {
            var urlPath = '{{ path('demo_view_user') }}';
            var data = "userid=" + userId;
            $.ajax({
                type: "GET",
                url: urlPath,
                data: data
            }).done(function( result ) {
                if(result.success) {
                    console.log(result.registrationdate);
                    $('#user_data_table').html('<table width="100%"><thead><th>User Id</th><th>User Name</th><th>Registration date</th></thead><tbody><tr><td>'+ result.id +'</td><td>'+ result.username +'</td><td>'+ result.registrationdate.date+'</td></tr></tbody></table>');
                } else {
                    $('#user_data_table').html('<div class="alert-message">Sorry, no records found!</div>');
                }
            });
        }
     </script>

{% endblock %}

src/Acme/DemoBundle/Resources/views/layout.html.twig
{% extends "TwigBundle::layout.html.twig" %}

{% block head %}
    <link rel="icon" sizes="16x16" href="{{ asset('favicon.ico') }}" />
    <link rel="stylesheet" href="{{ asset('bundles/acmedemo/css/demo.css') }}" />
{% endblock %}

{% block title 'Demo Bundle' %}

{% block body %}
    {% for flashMessage in app.session.flashbag.get('notice') %}
        <div class="flash-message">
            <em>Notice</em>: {{ flashMessage }}
        </div>
    {% endfor %}

    {% block content_header %}
        <ul id="menu">
            {% block content_header_more %}
                <li><a href="{{ path('demo_list_user') }}">Demo Home</a></li>
            {% endblock %}
        </ul>

        <div style="clear: both"></div>
    {% endblock %}

    <div class="block">
        {% block content %}{% endblock %}
    </div>

    {% if code is defined %}
        <h2>Code behind this page</h2>
        <div class="block">
            <div class="symfony-content">{{ code|raw }}</div>
        </div>
    {% endif %}
{% endblock %}